services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vendor\LayoutPresetBundle\:
    resource: '../../*'
    exclude: '../../{Resources,ContaoManager,DependencyInjection,Entity,Tests}'
